// <auto-generated />
using CleverAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CleverAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180508085311_AirContaminantsRU_20180507_00")]
    partial class AirContaminantsRU_20180507_00
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("CleverAPI.Models.AirContaminant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("ApproximateSafeExposureLevel");

                    b.Property<int?>("HazardClass");

                    b.Property<decimal?>("MaximumPermissibleConcentrationDailyAverage");

                    b.Property<decimal?>("MaximumPermissibleConcentrationOneTimeMaximum");

                    b.Property<string>("Name");

                    b.Property<string>("NumberCAS");

                    b.HasKey("Id");

                    b.ToTable("AirContaminant");
                });

            modelBuilder.Entity("CleverAPI.Models.AirContaminantKK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("ApproximateSafeExposureLevel");

                    b.Property<int?>("Code");

                    b.Property<string>("Formula");

                    b.Property<int?>("HazardClass");

                    b.Property<decimal?>("MaximumPermissibleConcentrationDailyAverage");

                    b.Property<decimal?>("MaximumPermissibleConcentrationOneTimeMaximum");

                    b.Property<string>("Name");

                    b.Property<string>("NumberCAS");

                    b.HasKey("Id");

                    b.ToTable("AirContaminantKK");
                });

            modelBuilder.Entity("CleverAPI.Models.AirContaminantRU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("ApproximateSafeExposureLevel");

                    b.Property<int?>("Code");

                    b.Property<string>("Formula");

                    b.Property<int?>("HazardClass");

                    b.Property<decimal?>("MaximumPermissibleConcentrationDailyAverage");

                    b.Property<decimal?>("MaximumPermissibleConcentrationOneTimeMaximum");

                    b.Property<string>("Name");

                    b.Property<string>("NumberCAS");

                    b.HasKey("Id");

                    b.ToTable("AirContaminantRU");
                });

            modelBuilder.Entity("CleverAPI.Models.CATO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AreaType");

                    b.Property<string>("Code");

                    b.Property<int?>("EgovId");

                    b.Property<DateTime?>("ExpiredDateTime");

                    b.Property<string>("NameEN");

                    b.Property<string>("NameKK");

                    b.Property<string>("NameRU");

                    b.Property<int?>("Parent");

                    b.HasKey("Id");

                    b.ToTable("CATO");
                });
#pragma warning restore 612, 618
        }
    }
}
