//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clever.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clever.Resources.Controllers.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AirContaminantKK {
            get {
                return ResourceManager.GetString("AirContaminantKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AirContaminantRU {
            get {
                return ResourceManager.GetString("AirContaminantRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AirContaminantsKK {
            get {
                return ResourceManager.GetString("AirContaminantsKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AirContaminantsRU {
            get {
                return ResourceManager.GetString("AirContaminantsRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CATO {
            get {
                return ResourceManager.GetString("CATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CompaniesKK {
            get {
                return ResourceManager.GetString("CompaniesKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CompanyKK {
            get {
                return ResourceManager.GetString("CompanyKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string dry {
            get {
                return ResourceManager.GetString("dry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string emissionsInGS {
            get {
                return ResourceManager.GetString("emissionsInGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string emissionsInT {
            get {
                return ResourceManager.GetString("emissionsInT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string flammable {
            get {
                return ResourceManager.GetString("flammable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaA {
            get {
                return ResourceManager.GetString("FormulaA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaAAbove {
            get {
                return ResourceManager.GetString("FormulaAAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaAc {
            get {
                return ResourceManager.GetString("FormulaAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaAFact {
            get {
                return ResourceManager.GetString("FormulaAFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaArW {
            get {
                return ResourceManager.GetString("FormulaArW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaAstrat {
            get {
                return ResourceManager.GetString("FormulaAstrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaAt {
            get {
                return ResourceManager.GetString("FormulaAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaAv {
            get {
                return ResourceManager.GetString("FormulaAv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaB {
            get {
                return ResourceManager.GetString("FormulaB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaBg {
            get {
                return ResourceManager.GetString("FormulaBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaBgf {
            get {
                return ResourceManager.GetString("FormulaBgf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaBgs {
            get {
                return ResourceManager.GetString("FormulaBgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaBno2 {
            get {
                return ResourceManager.GetString("FormulaBno2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaBp {
            get {
                return ResourceManager.GetString("FormulaBp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaBpg {
            get {
                return ResourceManager.GetString("FormulaBpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaBt {
            get {
                return ResourceManager.GetString("FormulaBt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCCO {
            get {
                return ResourceManager.GetString("FormulaCCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCcoDg {
            get {
                return ResourceManager.GetString("FormulaCcoDg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCcoSgt {
            get {
                return ResourceManager.GetString("FormulaCcoSgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCh2s {
            get {
                return ResourceManager.GetString("FormulaCh2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCiDg {
            get {
                return ResourceManager.GetString("FormulaCiDg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCjCO {
            get {
                return ResourceManager.GetString("FormulaCjCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCjNOx {
            get {
                return ResourceManager.GetString("FormulaCjNOx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCjSO2 {
            get {
                return ResourceManager.GetString("FormulaCjSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCjT {
            get {
                return ResourceManager.GetString("FormulaCjT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCjTB {
            get {
                return ResourceManager.GetString("FormulaCjTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCjZCO {
            get {
                return ResourceManager.GetString("FormulaCjZCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCjZNO {
            get {
                return ResourceManager.GetString("FormulaCjZNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCjZNO2 {
            get {
                return ResourceManager.GetString("FormulaCjZNO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCjZSO2 {
            get {
                return ResourceManager.GetString("FormulaCjZSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCno2 {
            get {
                return ResourceManager.GetString("FormulaCno2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCNOx {
            get {
                return ResourceManager.GetString("FormulaCNOx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCoal {
            get {
                return ResourceManager.GetString("FormulaCoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCr {
            get {
                return ResourceManager.GetString("FormulaCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCSO2 {
            get {
                return ResourceManager.GetString("FormulaCSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCsSa {
            get {
                return ResourceManager.GetString("FormulaCsSa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaCTB {
            get {
                return ResourceManager.GetString("FormulaCTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaD {
            get {
                return ResourceManager.GetString("FormulaD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaD1 {
            get {
                return ResourceManager.GetString("FormulaD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDd {
            get {
                return ResourceManager.GetString("FormulaDd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDdg {
            get {
                return ResourceManager.GetString("FormulaDdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDelta {
            get {
                return ResourceManager.GetString("FormulaDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDf {
            get {
                return ResourceManager.GetString("FormulaDf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDfact {
            get {
                return ResourceManager.GetString("FormulaDfact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDgs {
            get {
                return ResourceManager.GetString("FormulaDgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDn {
            get {
                return ResourceManager.GetString("FormulaDn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDnom {
            get {
                return ResourceManager.GetString("FormulaDnom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDo {
            get {
                return ResourceManager.GetString("FormulaDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDu {
            get {
                return ResourceManager.GetString("FormulaDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDv {
            get {
                return ResourceManager.GetString("FormulaDv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDyx {
            get {
                return ResourceManager.GetString("FormulaDyx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaDyxNo2 {
            get {
                return ResourceManager.GetString("FormulaDyxNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaE {
            get {
                return ResourceManager.GetString("FormulaE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaEta {
            get {
                return ResourceManager.GetString("FormulaEta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaF {
            get {
                return ResourceManager.GetString("FormulaF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaFgvs {
            get {
                return ResourceManager.GetString("FormulaFgvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaFparam {
            get {
                return ResourceManager.GetString("FormulaFparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaFuelTransfer {
            get {
                return ResourceManager.GetString("FormulaFuelTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaG {
            get {
                return ResourceManager.GetString("FormulaG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaG1 {
            get {
                return ResourceManager.GetString("FormulaG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGas {
            get {
                return ResourceManager.GetString("FormulaGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGasVolumeEmissionValues {
            get {
                return ResourceManager.GetString("FormulaGasVolumeEmissionValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGdg {
            get {
                return ResourceManager.GetString("FormulaGdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGdgCO {
            get {
                return ResourceManager.GetString("FormulaGdgCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGdgNOX {
            get {
                return ResourceManager.GetString("FormulaGdgNOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGi {
            get {
                return ResourceManager.GetString("FormulaGi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGno2 {
            get {
                return ResourceManager.GetString("FormulaGno2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGr {
            get {
                return ResourceManager.GetString("FormulaGr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGrGrs {
            get {
                return ResourceManager.GetString("FormulaGrGrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGrGrsS {
            get {
                return ResourceManager.GetString("FormulaGrGrsS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGrKs {
            get {
                return ResourceManager.GetString("FormulaGrKs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGrKsS {
            get {
                return ResourceManager.GetString("FormulaGrKsS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGrPhg {
            get {
                return ResourceManager.GetString("FormulaGrPhg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGrPhgS {
            get {
                return ResourceManager.GetString("FormulaGrPhgS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGsa {
            get {
                return ResourceManager.GetString("FormulaGsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGtg {
            get {
                return ResourceManager.GetString("FormulaGtg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGv {
            get {
                return ResourceManager.GetString("FormulaGv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGw {
            get {
                return ResourceManager.GetString("FormulaGw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaGwDg {
            get {
                return ResourceManager.GetString("FormulaGwDg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaH {
            get {
                return ResourceManager.GetString("FormulaH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaHc {
            get {
                return ResourceManager.GetString("FormulaHc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaHeatPowerThermalPowerPlantsCoal {
            get {
                return ResourceManager.GetString("FormulaHeatPowerThermalPowerPlantsCoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaHeatPowerThermalPowerPlantsCoalNorm {
            get {
                return ResourceManager.GetString("FormulaHeatPowerThermalPowerPlantsCoalNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaHeatPowerThermalPowerPlantsCoalZ {
            get {
                return ResourceManager.GetString("FormulaHeatPowerThermalPowerPlantsCoalZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaHrW {
            get {
                return ResourceManager.GetString("FormulaHrW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Formulai1 {
            get {
                return ResourceManager.GetString("Formulai1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Formulai2 {
            get {
                return ResourceManager.GetString("Formulai2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaICO {
            get {
                return ResourceManager.GetString("FormulaICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaINO {
            get {
                return ResourceManager.GetString("FormulaINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaINO2 {
            get {
                return ResourceManager.GetString("FormulaINO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaISO2 {
            get {
                return ResourceManager.GetString("FormulaISO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaK {
            get {
                return ResourceManager.GetString("FormulaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaKd {
            get {
                return ResourceManager.GetString("FormulaKd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaKi {
            get {
                return ResourceManager.GetString("FormulaKi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaKiDg {
            get {
                return ResourceManager.GetString("FormulaKiDg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaKiMif {
            get {
                return ResourceManager.GetString("FormulaKiMif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaKiO {
            get {
                return ResourceManager.GetString("FormulaKiO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaKn {
            get {
                return ResourceManager.GetString("FormulaKn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaKPDKA {
            get {
                return ResourceManager.GetString("FormulaKPDKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaKzy {
            get {
                return ResourceManager.GetString("FormulaKzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaL {
            get {
                return ResourceManager.GetString("FormulaL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaLv {
            get {
                return ResourceManager.GetString("FormulaLv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaM {
            get {
                return ResourceManager.GetString("FormulaM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMCO {
            get {
                return ResourceManager.GetString("FormulaMCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMCOY {
            get {
                return ResourceManager.GetString("FormulaMCOY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMgvs {
            get {
                return ResourceManager.GetString("FormulaMgvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMi {
            get {
                return ResourceManager.GetString("FormulaMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMiFact {
            get {
                return ResourceManager.GetString("FormulaMiFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMiFactCO {
            get {
                return ResourceManager.GetString("FormulaMiFactCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMiFactNOx {
            get {
                return ResourceManager.GetString("FormulaMiFactNOx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMiTg {
            get {
                return ResourceManager.GetString("FormulaMiTg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMiUv {
            get {
                return ResourceManager.GetString("FormulaMiUv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMNO {
            get {
                return ResourceManager.GetString("FormulaMNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMNO2 {
            get {
                return ResourceManager.GetString("FormulaMNO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMNO2Y {
            get {
                return ResourceManager.GetString("FormulaMNO2Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMNOx {
            get {
                return ResourceManager.GetString("FormulaMNOx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMNOxY {
            get {
                return ResourceManager.GetString("FormulaMNOxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMNOY {
            get {
                return ResourceManager.GetString("FormulaMNOY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMrPhgS {
            get {
                return ResourceManager.GetString("FormulaMrPhgS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMsKsS {
            get {
                return ResourceManager.GetString("FormulaMsKsS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMSO2 {
            get {
                return ResourceManager.GetString("FormulaMSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMSO2Y {
            get {
                return ResourceManager.GetString("FormulaMSO2Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMTB {
            get {
                return ResourceManager.GetString("FormulaMTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMTBY {
            get {
                return ResourceManager.GetString("FormulaMTBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaMZMY {
            get {
                return ResourceManager.GetString("FormulaMZMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaN {
            get {
                return ResourceManager.GetString("FormulaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNc {
            get {
                return ResourceManager.GetString("FormulaNc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNfact {
            get {
                return ResourceManager.GetString("FormulaNfact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNgvs {
            get {
                return ResourceManager.GetString("FormulaNgvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNgvsHol {
            get {
                return ResourceManager.GetString("FormulaNgvsHol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNi {
            get {
                return ResourceManager.GetString("FormulaNi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNnom {
            get {
                return ResourceManager.GetString("FormulaNnom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNoc {
            get {
                return ResourceManager.GetString("FormulaNoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNp {
            get {
                return ResourceManager.GetString("FormulaNp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNrW {
            get {
                return ResourceManager.GetString("FormulaNrW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNso2 {
            get {
                return ResourceManager.GetString("FormulaNso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNyy {
            get {
                return ResourceManager.GetString("FormulaNyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaNzy {
            get {
                return ResourceManager.GetString("FormulaNzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaO2 {
            get {
                return ResourceManager.GetString("FormulaO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaO2dg {
            get {
                return ResourceManager.GetString("FormulaO2dg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaOc {
            get {
                return ResourceManager.GetString("FormulaOc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaOrW {
            get {
                return ResourceManager.GetString("FormulaOrW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaP {
            get {
                return ResourceManager.GetString("FormulaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaPa {
            get {
                return ResourceManager.GetString("FormulaPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaPcp {
            get {
                return ResourceManager.GetString("FormulaPcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaPDK {
            get {
                return ResourceManager.GetString("FormulaPDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaPDV {
            get {
                return ResourceManager.GetString("FormulaPDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaPDVhol {
            get {
                return ResourceManager.GetString("FormulaPDVhol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaPo {
            get {
                return ResourceManager.GetString("FormulaPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaPsi {
            get {
                return ResourceManager.GetString("FormulaPsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaPsiNo2 {
            get {
                return ResourceManager.GetString("FormulaPsiNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaPv {
            get {
                return ResourceManager.GetString("FormulaPv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaPz {
            get {
                return ResourceManager.GetString("FormulaPz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaQ {
            get {
                return ResourceManager.GetString("FormulaQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaQ3 {
            get {
                return ResourceManager.GetString("FormulaQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaQ4 {
            get {
                return ResourceManager.GetString("FormulaQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaQgrs {
            get {
                return ResourceManager.GetString("FormulaQgrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaQgrsS {
            get {
                return ResourceManager.GetString("FormulaQgrsS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaQnr {
            get {
                return ResourceManager.GetString("FormulaQnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaQri {
            get {
                return ResourceManager.GetString("FormulaQri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaQrnNo2 {
            get {
                return ResourceManager.GetString("FormulaQrnNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaQsnr {
            get {
                return ResourceManager.GetString("FormulaQsnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaR {
            get {
                return ResourceManager.GetString("FormulaR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaRdpt {
            get {
                return ResourceManager.GetString("FormulaRdpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaRo {
            get {
                return ResourceManager.GetString("FormulaRo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaRoGvs {
            get {
                return ResourceManager.GetString("FormulaRoGvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaRoPhgKs {
            get {
                return ResourceManager.GetString("FormulaRoPhgKs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaRor {
            get {
                return ResourceManager.GetString("FormulaRor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaRoRGr {
            get {
                return ResourceManager.GetString("FormulaRoRGr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaRoSa {
            get {
                return ResourceManager.GetString("FormulaRoSa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Formulas {
            get {
                return ResourceManager.GetString("Formulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaSAbove {
            get {
                return ResourceManager.GetString("FormulaSAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaSc {
            get {
                return ResourceManager.GetString("FormulaSc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaSrW {
            get {
                return ResourceManager.GetString("FormulaSrW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaSs {
            get {
                return ResourceManager.GetString("FormulaSs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Formulat {
            get {
                return ResourceManager.GetString("Formulat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Formulat0 {
            get {
                return ResourceManager.GetString("Formulat0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTdelta {
            get {
                return ResourceManager.GetString("FormulaTdelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTi {
            get {
                return ResourceManager.GetString("FormulaTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTitleAnnualEmissionsPollutants {
            get {
                return ResourceManager.GetString("FormulaTitleAnnualEmissionsPollutants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTitleCalcMassConcentrationsPollutants {
            get {
                return ResourceManager.GetString("FormulaTitleCalcMassConcentrationsPollutants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTitleEmissionsPollutants {
            get {
                return ResourceManager.GetString("FormulaTitleEmissionsPollutants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTitleEstimatedFuelConsumption {
            get {
                return ResourceManager.GetString("FormulaTitleEstimatedFuelConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTitleRecalculationDryToWorking {
            get {
                return ResourceManager.GetString("FormulaTitleRecalculationDryToWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTitleVolumeOfDryFlueGases {
            get {
                return ResourceManager.GetString("FormulaTitleVolumeOfDryFlueGases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTk {
            get {
                return ResourceManager.GetString("FormulaTk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulatKs {
            get {
                return ResourceManager.GetString("FormulatKs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Formulatn {
            get {
                return ResourceManager.GetString("Formulatn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTog {
            get {
                return ResourceManager.GetString("FormulaTog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTogm {
            get {
                return ResourceManager.GetString("FormulaTogm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTsvr {
            get {
                return ResourceManager.GetString("FormulaTsvr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaTz {
            get {
                return ResourceManager.GetString("FormulaTz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaUm {
            get {
                return ResourceManager.GetString("FormulaUm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaUmHol {
            get {
                return ResourceManager.GetString("FormulaUmHol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaUps {
            get {
                return ResourceManager.GetString("FormulaUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaUpsNo2 {
            get {
                return ResourceManager.GetString("FormulaUpsNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaV {
            get {
                return ResourceManager.GetString("FormulaV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaV1 {
            get {
                return ResourceManager.GetString("FormulaV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaV1gvs {
            get {
                return ResourceManager.GetString("FormulaV1gvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaV1gvsov {
            get {
                return ResourceManager.GetString("FormulaV1gvsov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaV1Ks {
            get {
                return ResourceManager.GetString("FormulaV1Ks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaV1vp {
            get {
                return ResourceManager.GetString("FormulaV1vp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVb {
            get {
                return ResourceManager.GetString("FormulaVb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVcr {
            get {
                return ResourceManager.GetString("FormulaVcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVdg {
            get {
                return ResourceManager.GetString("FormulaVdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVe {
            get {
                return ResourceManager.GetString("FormulaVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVgdg {
            get {
                return ResourceManager.GetString("FormulaVgdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVgf {
            get {
                return ResourceManager.GetString("FormulaVgf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVgraf {
            get {
                return ResourceManager.GetString("FormulaVgraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVgrPhg {
            get {
                return ResourceManager.GetString("FormulaVgrPhg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVgvs {
            get {
                return ResourceManager.GetString("FormulaVgvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVh2o {
            get {
                return ResourceManager.GetString("FormulaVh2o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVi {
            get {
                return ResourceManager.GetString("FormulaVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVk {
            get {
                return ResourceManager.GetString("FormulaVk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVkKs {
            get {
                return ResourceManager.GetString("FormulaVkKs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVks {
            get {
                return ResourceManager.GetString("FormulaVks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVksS {
            get {
                return ResourceManager.GetString("FormulaVksS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVn2 {
            get {
                return ResourceManager.GetString("FormulaVn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVpg {
            get {
                return ResourceManager.GetString("FormulaVpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVphg {
            get {
                return ResourceManager.GetString("FormulaVphg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVphgS {
            get {
                return ResourceManager.GetString("FormulaVphgS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVr {
            get {
                return ResourceManager.GetString("FormulaVr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVrGr {
            get {
                return ResourceManager.GetString("FormulaVrGr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVro2 {
            get {
                return ResourceManager.GetString("FormulaVro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVsa {
            get {
                return ResourceManager.GetString("FormulaVsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVsr {
            get {
                return ResourceManager.GetString("FormulaVsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVsst {
            get {
                return ResourceManager.GetString("FormulaVsst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVstr {
            get {
                return ResourceManager.GetString("FormulaVstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVtg {
            get {
                return ResourceManager.GetString("FormulaVtg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVtr {
            get {
                return ResourceManager.GetString("FormulaVtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaVvg {
            get {
                return ResourceManager.GetString("FormulaVvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaW {
            get {
                return ResourceManager.GetString("FormulaW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaWr {
            get {
                return ResourceManager.GetString("FormulaWr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaYco {
            get {
                return ResourceManager.GetString("FormulaYco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaYno2 {
            get {
                return ResourceManager.GetString("FormulaYno2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaYno2Nom {
            get {
                return ResourceManager.GetString("FormulaYno2Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaZ {
            get {
                return ResourceManager.GetString("FormulaZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaZg {
            get {
                return ResourceManager.GetString("FormulaZg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaКphg {
            get {
                return ResourceManager.GetString("FormulaКphg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormulaКphgS {
            get {
                return ResourceManager.GetString("FormulaКphgS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string gasEngine {
            get {
                return ResourceManager.GetString("gasEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string gasTurbine {
            get {
                return ResourceManager.GetString("gasTurbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string liquidSlagRemoval {
            get {
                return ResourceManager.GetString("liquidSlagRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NameKK {
            get {
                return ResourceManager.GetString("NameKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NameRU {
            get {
                return ResourceManager.GetString("NameRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Parse {
            get {
                return ResourceManager.GetString("Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string requiredFuelMass {
            get {
                return ResourceManager.GetString("requiredFuelMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string selectOneOption {
            get {
                return ResourceManager.GetString("selectOneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string solidAshRemoval {
            get {
                return ResourceManager.GetString("solidAshRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string targetMassOfFuel {
            get {
                return ResourceManager.GetString("targetMassOfFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string withoutSteam {
            get {
                return ResourceManager.GetString("withoutSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string withoutSuperheater {
            get {
                return ResourceManager.GetString("withoutSuperheater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string withSteam {
            get {
                return ResourceManager.GetString("withSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string withSuperheater {
            get {
                return ResourceManager.GetString("withSuperheater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string working {
            get {
                return ResourceManager.GetString("working", resourceCulture);
            }
        }
    }
}
